### ISSUE TITLE
Peer certificate cannot be authenticated with given CA certificates

### ISSUE THREAD

**Issue by adrivansoft** [mariodian/bitfinex-auto-lend#1]
![image](https://user-images.githubusercontent.com/12457752/28144518-83c176d2-679e-11e7-9e2e-b1ad9129ae43.png)

I'm getting this when running via xampp on windows 10

P.S. I fixed it myself. It was an error with xampp which was solved using this approach - https://stackoverflow.com/questions/29822686/curl-error-60-ssl-certificate-unable-to-get-local-issuer-certificate

**Comment by mariodian** [comment]
Thanks for letting everyone know! You could have also set CURL_VERIFYPEER to FALSE in bitfinex.php I think.

Closing the issue.

**Comment by adrivansoft** [comment]
I tried disabling that including CURLOPT_SSL_VERIFYHOST in both the ssl and non ssl related functions in bitfinex.php and it didn't work. I also tried specifying CURLOPT_CAINFO and it still didn't work so I ended up editing php.ini.

I find it very weird because declaring those should have been enough to fix it without the need to edit php.ini.
